name: test-integration-localstack

on:
  pull_request:
    branches: [master, feature]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1]
          docker pull localstack/localstack
          localstack start -d

          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"
      - name: Deploy infrastructure
        run: |
          bin/deploy.sh
      - name: Run integration tests against LocalStack
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: |
          python -m pytest tests/integration
      - name: Show localstack logs
        if: always()
        run: |
          localstack logs
